{
 "title": "H3C SNMP",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "job", "label": "Job", "query": { "query": "label_values(sysDescr,job)" } },
   { "name": "interfaces", "query": "WAN1, VLAN1" }
  ]
 },
 "panels": [
  {
   "title": "Brief Info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true
  },
  {
   "title": "Usage",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hh3cEntityExtCpuUsage{job=\"$job\"}",
     "legendFormat": "CPU"
    },
    {
     "expr": "hh3cEntityExtMemUsage{job=\"$job\"}",
     "legendFormat": "MEM"
    }
   ]
  },
  {
   "title": "Sys Name",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 2, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sysName{job=\"$job\"}",
     "legendFormat": "{{sysName}}"
    }
   ]
  },
  {
   "title": "Sys Up Time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sysUpTime{job=\"$job\"} / 100",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Interface Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "targets": [
    {
     "expr": "rate(ifHCInOctets{job=\"$job\", ifDescr=~\"$interfaces\"}[$__rate_interval]) * 8",
     "legendFormat": "{{ifDescr}} In"
    },
    {
     "expr": "rate(ifHCOutOctets{job=\"$job\", ifDescr=~\"$interfaces\"}[$__rate_interval]) * -8",
     "legendFormat": "{{ifDescr}} Out"
    }
   ]
  },
  {
   "title": "Interfaces",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "expr": "ifMtu{job=\"$job\"}",
     "legendFormat": "{{ifDescr}}"
    },
    {
     "expr": "ifOperStatus{job=\"$job\"}",
     "legendFormat": "{{ifDescr}}"
    },
    {
     "expr": "label_replace(irate(ifHCInOctets{job=\"$job\"}[$__interval]) * 8, \"__name__\", \"InOctets\", \"\", \"(.*)\")",
     "legendFormat": "{{ifDescr}}"
    },
    {
     "expr": "label_replace(irate(ifHCOutOctets{job=\"$job\"}[$__interval]) * 8, \"__name__\", \"OutOctets\", \"\", \"(.*)\")",
     "legendFormat": "{{ifDescr}}"
    }
   ]
  },
  { "title": "CPU & MEM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg_over_time(hh3cEntityExtCpuUsage{job=\"snmp\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MEM Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg_over_time(hh3cEntityExtMemUsage{job=\"snmp\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}